### ISSUE TITLE
Option to restore legacy top navbar links

### ISSUE THREAD

**Issue by ghost** [tersiswilvin/Roblox-2019-Old-Theme#5]
Hi, it would be amazing to see the option to change the 'Create' button back to 'Develop' and 'Robux' back to 'Trade'!

Another suggestion is to bring back 'Chat and Party' text on Chat tab. Maybe bring back old group layout (I would imagine that would be hard to code back as it's had a complete overhaul)

I'm on experimental build 20230710.1.3 and the only bugs I'm experiencing are the OBC theme, the Premium to Builders Club not working and the 'Hello,' next to my username on the home screen isn't working.

Thanks for this awesome extension, I only discovered it today, as I used to have a Stylish style for Roblox 2018 but it's not well maintained and this one seemed to be amazing and once I tried it, I'm loving it! With a quick change of settings, I'm already getting the emotional sense of nostalgia from when I was younger playing Roblox Jailbreak and changing my Avatar after school!

**Comment by tersiswilvin** [comment]
Hi MX-Mic,
    Thank you for your suggestions! I am planning in the future for navigation options and chat options when I get my hands on a working chat, while I have no idea when it will come to light as of now I do hope to start on it when I have the time to. I am curious what issue you're facing with the OBC theme and with the hello text not displaying, as for "Premium to Builders Club", it only applies to btroblox navigation at this time. If you have any other suggestions or ideas feel free to let me know as I am open for room to new suggestions and features.

**Comment by ghost** [comment]
If needed for reference the extensions for Roblox I have installed are DashBlox, Roblox+, BTRoblox and Click-To-Remove-Element. I've tried disabling these and it's not fixed anything. I've removed elements of new updates I don't like by Roblox using CTRE, but since some elements use class names of other elements, it messes the good elements up so hopefully (as you mentioned) the elements I don't like get an option to be removed in your style, if you know what I mean!

The problem with the OBC theme is this:
![Capture](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/77752310/8b795d64-ff31-4ce1-b080-7838bc3ed2f6)

Games in profile has changed back to experiences and even with BTR's profile change on, the text hasn't changed to white to be readable. There's also a blue square thing where the '@' next to my username was supposed to be (because in the experimental version you removed it, which is nice.

Looking forward to your new updates!

**Comment by tersiswilvin** [comment]
I'll take a look into fixing these issues within the next update period.

**Comment by tersiswilvin** [comment]
I believe I have fixed majority of the issues stated in the recent update?

**Comment by ghost** [comment]
> I believe I have fixed majority of the issues stated in the recent update?

I take a look this afternoon. I'll close the issue thread if things are fixed. Cheers!

**Comment by ghost** [comment]
All fixed now, the only thing is that the hello text only works when DashBlox is enabled with Classic homepage is enabled, but I'm fine with that.

**Comment by ghost** [comment]
The only thing about the OBC thing I can find now is in the Groups the titles in all group related pages and maybe other pages are not white to be readable but mostly fixed.

**Comment by tersiswilvin** [comment]
I fixed the header colors with obc theme enabled in the recent update.

**Comment by tersiswilvin** [comment]
Hi I see you reopened this issue, is there any other issues you're still facing?

**Comment by MX-Mic** [comment]
I probably did this by accident, but while I'm at it, have you got any ideas on how you're going to get the status updates on My Feed working?

**Comment by ghost** [comment]
#37

**Comment by ghost** [comment]
#47
